//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Mvc.Examples.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kendo.Mvc.Examples.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرم افزار باسکول توزین نگار.
        /// </summary>
        public static string indexH1 {
            get {
                return ResourceManager.GetString("indexH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتوماسیون سیستم ها توزین جاده ای.
        /// </summary>
        public static string indexP1 {
            get {
                return ResourceManager.GetString("indexP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باسکول صنعتی.
        /// </summary>
        public static string indexP10 {
            get {
                return ResourceManager.GetString("indexP10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باسکول از نظر ساختاری تفاوت چندانی با ترازو ندارد و از همان ساختار لودسل (حسگر توزین) برای اندازه گیری استفاده می کند. تفاوت در بازه ظرفیت توزین است که باسکول ها اوزان بسیار بیشتری را نسبت به ترازو می سنجند. از نظر تاریخی نیز باید استفاده از باسکول را با ترازو یکی دانست..
        /// </summary>
        public static string indexP11 {
            get {
                return ResourceManager.GetString("indexP11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیتابیس پر قدرت اس کیو ال سرور.
        /// </summary>
        public static string indexP2 {
            get {
                return ResourceManager.GetString("indexP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نصب شده در کلیه نقاط ایران بهمراه خدمات 24 ساعته.
        /// </summary>
        public static string indexP3 {
            get {
                return ResourceManager.GetString("indexP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش گیری متنوع بهمراه خروجی اکسل و پی دی اف.
        /// </summary>
        public static string indexP4 {
            get {
                return ResourceManager.GetString("indexP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت وزن بدون دخالت کاربر و قابلیت اتصال به کلیه نشاندهنده های توزین موجود در بازار.
        /// </summary>
        public static string indexP5 {
            get {
                return ResourceManager.GetString("indexP5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشاندهنده باسکول.
        /// </summary>
        public static string indexP6 {
            get {
                return ResourceManager.GetString("indexP6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وظیفه اصلی نشان دهنده وزن در هر ترازو یا باسکول الکترونیکی دریافت اطلاعات وزن خوانده شده از لودسل ها و تبدیل آن به رقم  و نمایش وزن می باشد.
        ///            بدین ترتیب که سیم خروجی از جانکش باکس به نمایشگر باسکول متصل میگردد و عدد وزن بر روی نمایشگر نشان داده می شود ..
        /// </summary>
        public static string indexP7 {
            get {
                return ResourceManager.GetString("indexP7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لودسل (Load Cell).
        /// </summary>
        public static string indexP8 {
            get {
                return ResourceManager.GetString("indexP8", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لودسل یا Load Cell یک نوع حسـگر الکترونیکی برای اندازه‌گیری وزن است که در سیـستم‌های تـوزین مورد استـفاده قـرار می‌گیرد. این محـصول بالا و پایین رفتن  وزن را بر اساس تغییر ولتاژ طبق وزن بار اعمال شده حس می‌کند و آن را به نمایشگر الکتـرونیـکی منتـقل می‌کنند.
        /// </summary>
        public static string indexP9
        {
            get
            {
                return ResourceManager.GetString("indexP9", resourceCulture);
            }
        }
        public static string indexP12
        {
            get
            {
                return ResourceManager.GetString("indexP12", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string LangName {
            get {
                return ResourceManager.GetString("LangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانه.
        /// </summary>
        public static string menu1 {
            get {
                return ResourceManager.GetString("menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نرم افزار باسکول.
        /// </summary>
        public static string menu2 {
            get {
                return ResourceManager.GetString("menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجهیزات باسکول.
        /// </summary>
        public static string menu3 {
            get {
                return ResourceManager.GetString("menu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحت وب.
        /// </summary>
        public static string menu4 {
            get {
                return ResourceManager.GetString("menu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارتباط با ما.
        /// </summary>
        public static string menu5 {
            get {
                return ResourceManager.GetString("menu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات بیشتر.
        /// </summary>
        public static string more__information {
            get {
                return ResourceManager.GetString("more _information", resourceCulture);
            }
        }
    }
}
